import { store } from '../state/store'
import type { Studio } from '../audio/Studio'
import type { NoteEvent } from '../types'

export interface RecordedEvent extends NoteEvent {
  offset: number // seconds from the start of the recording
}

/**
 * Event recorder / looper. Records NoteEvents (not audio) and replays them
 * through the engine with look-ahead scheduling on the audio clock.
 */
export class Recorder {
  private studio: Studio | null = null
  private events: RecordedEvent[] = []
  private recStart = 0
  private state: 'idle' | 'recording' | 'playing' = 'idle'
  private duration = 0
  private playStart = 0
  private playIdx = 0
  private timer: number | null = null
  private loop = false

  attach(s: Studio) {
    this.studio = s
  }

  get isRecording() {
    return this.state === 'recording'
  }

  onNote(e: NoteEvent) {
    if (this.state !== 'recording' || !this.studio) return
    // ignore notes generated by playback itself
    if (store.get().inputSource === 'playback') return
    this.events.push({ ...e, bend: store.get().bend, offset: Math.max(0, e.time - this.recStart) })
    store.set({ recordedEvents: this.events.length })
  }

  toggleRecord() {
    if (this.state === 'recording') this.stop()
    else this.record()
  }

  record() {
    if (!this.studio) return
    this.stopPlayback()
    this.events = []
    this.recStart = this.studio.ctx.currentTime
    this.state = 'recording'
    store.set({ recorder: 'recording', recordedEvents: 0, recordDuration: 0 })
  }

  stop() {
    if (!this.studio) return
    if (this.state === 'recording') {
      // duration: last event + a musical tail, rounded up to the next beat
      const beat = 60 / store.get().bpm
      const raw = Math.max(this.studio.ctx.currentTime - this.recStart, this.events.length ? this.events[this.events.length - 1].offset + 0.5 : 0)
      this.duration = this.events.length ? Math.ceil(raw / beat) * beat : 0
      this.state = 'idle'
      store.set({ recorder: 'idle', recordDuration: this.duration })
    } else if (this.state === 'playing') {
      this.stopPlayback()
    }
  }

  play() {
    if (!this.studio || !this.events.length) return
    this.stopPlayback()
    this.state = 'playing'
    this.playStart = this.studio.ctx.currentTime + 0.05
    this.playIdx = 0
    store.set({ recorder: 'playing', playheadStamp: performance.now() })
    this.timer = window.setInterval(() => this.schedule(), 25)
  }

  setLoop(on: boolean) {
    this.loop = on
    store.set({ recorderLoop: on })
  }

  clear() {
    this.stopPlayback()
    this.events = []
    this.duration = 0
    this.state = 'idle'
    store.set({ recorder: 'idle', recordedEvents: 0, recordDuration: 0 })
  }

  /** 0..1 progress of playback for the timeline */
  get position(): number {
    if (this.state !== 'playing' || !this.studio || this.duration <= 0) return 0
    const t = this.studio.ctx.currentTime - this.playStart
    return Math.max(0, Math.min(1, (t % this.duration) / this.duration))
  }

  get length(): number {
    return this.duration
  }

  get eventList(): readonly RecordedEvent[] {
    return this.events
  }

  private stopPlayback() {
    if (this.timer !== null) window.clearInterval(this.timer)
    this.timer = null
    if (this.state === 'playing') {
      this.state = 'idle'
      store.set({ recorder: 'idle' })
    }
  }

  private schedule() {
    const s = this.studio
    if (!s || this.state !== 'playing') return
    const now = s.ctx.currentTime
    const horizon = now + 0.12
    while (this.playIdx < this.events.length) {
      const e = this.events[this.playIdx]
      const t = this.playStart + e.offset
      if (t > horizon) break
      if (t >= now - 0.02) this.fire(e, t)
      this.playIdx++
    }
    if (this.playIdx >= this.events.length) {
      const endTime = this.playStart + this.duration
      if (this.loop) {
        if (endTime < horizon) {
          this.playStart = endTime
          this.playIdx = 0
          store.set({ playheadStamp: performance.now() })
        }
      } else if (now >= endTime) {
        this.stopPlayback()
      }
    }
  }

  private fire(e: RecordedEvent, time: number) {
    const s = this.studio
    if (!s) return
    store.set({ inputSource: 'playback' })
    s.guitar.setBend(e.string, e.bend)
    s.guitar.playNote(e.string, e.fret, {
      velocity: e.velocity,
      technique: e.technique,
      palmMute: e.palmMute,
      time,
      chord: e.chord,
    })
  }
}
